### ISSUE TITLE
After logging in with the extension, the next screen comes up blank. 

### ISSUE THREAD

**Issue by tomasz-salesforce** [jhegele/tab-einstein-scenarios#27]
I'm able to login to my org but after I get a message that I successfully logged in, I'm then able to select a deployed model. After I select any model I get the blank screen as attached in the image.

![Screen Shot 2020-06-16 at 4 14 58 PM](https://user-images.githubusercontent.com/36003527/84823587-9844a680-afec-11ea-8ef3-4614d428fe9c.png)

**Comment by jhegele** [comment]
Hey @tomasz-salesforce, thanks for logging this. My suspicion is that you might be logging into a Salesforce org where you don't have rights grant permissions to a Connected App. This has happened to me before when I first login to my work computer. Salesforce establishes a session with our internal org and, if I try to add the extension, it uses that internal org (where I don't have enough permissions) rather than my demo org (where I have admin rights).

Try to login to whatever Salesforce org you want to use with the extension first, then load the extension and see what happens. If that doesn't work, let me know and I'll take a look.

**Comment by jhegele** [comment]
This was an issue where there were no Tableau parameters in the dashboard. The extension assumed that there would be at least one parameter and silently failed when none could be found.

Add error messaging that prevents the user from entering the setup phase with no Tableau parameters on the dashboard. Also updated string similarity code to avoid assuming that there would be at least one parameter that meets the 70% similarity criteria.

Issue should be resolved in [v0.3.1](https://github.com/jhegele/tab-einstein-scenarios/tree/v0.3.1-beta). Closing this issue.
